#!/bin/bash

# Check if number of arguments is less than 4, display usage
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning arguments to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Check if the file exists
if [ ! -f "$FILE_PATH" ]; then
    echo "Error: File '$FILE_PATH' not found."
    exit 1
fi

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "${USERNAME}@${SERVER_IP}:~/"

# Check if scp command succeeded
if [ $? -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi
