#!/usr/bin/env bash
# Sets up a new Ubuntu system by installing Nginx
# Configures Nginx to listen on port 80
# Creates a web page displaying "Hello World!" and
# sets up a redirect for /redirect_me to a YouTube video

echo -e "Updating package lists and installing Nginx...\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

# Provides feedback that package updates and Nginx installation are in progress

echo -e "\nPerforming additional setup tasks...\n"

# Initiates the Nginx service
sudo service nginx start

# Configures the firewall to allow Nginx traffic
sudo ufw allow 'Nginx HTTP'

# Adjusts file permissions and ownership for ease of editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Saves a copy of the default index file for backup purposes
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Updates the index file to display "Hello World!"
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Adds a redirection rule for /redirect_me to a YouTube URL
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com permanent;' /etc/nginx/sites-available/default

# Restarts Nginx to apply the new configuration
sudo service nginx restart

echo -e "\nSetup is complete.\n"

# Indicates that the setup process has finished
