#!/usr/bin/env bash
# Pings an IP address passed as an argument

# Check if the number of arguments passed is not equal to 1
if [ "$#" -ne 1 ]; then
    echo "Usage: $(basename "$0") {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address=$1

# Pings the IP address 5 times
ping -c 5 "$ip_address"
