#!/usr/bin/env bash
# Makes sure that Nginx is listening on port 80

# Update package lists
sudo apt-get update

# Install Nginx if not already installed
sudo apt-get install -y nginx

# Ensure Nginx is configured to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 0.0.0.0:80 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80 default_server;/' /etc/nginx/sites-available/default

# Ensure Nginx is running and restart it to apply changes
sudo service nginx restart
