#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements

# Checks if the script is ran with superuser privilege
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root" 
    exit 1
fi

# Copy /etc/hosts to a new file in the home directory
cp /etc/hosts ~/hosts.new

# Using sed to configure localhost and facebook.com resolutions in the new hosts file
sed -i 's/^127\.0\.0\.1.*$/127.0.0.2 localhost/' ~/hosts.new
sed -i 's/^127\.0\.0\.1.*facebook\.com.*$/8.8.8.8 facebook.com/' ~/hosts.new

# Copy the modified hosts file back to /etc/hosts
cp -f ~/hosts.new /etc/hosts
